#!/bin/bash
# Cleans out all docker images, containers and container data.

# Check ran by root, if not, elevate to root
if [[ $EUID -ne 0 ]]; then
    sudo su -s "$0"
    exit
fi

# Stop all containers
echo "Stopping containers."
docker ps | grep "_container" | awk '{print $1}' | xargs docker stop

# Remove containers
echo "Removing containers"
docker ps -a | grep "_container" | awk '{print $1}' | xargs docker rm

# Remove images
echo "Removing images"
docker rmi bungee
docker rmi spigotmc

# Clean data
echo "Removing all data files."
rm -rf /srv/server-data
rm -rf /opt/buildtools
rm -ff /opt/java

echo "Done!"
