#!/bin/bash
# Cleans out all docker images, containers and container data.

# Check ran by root, if not, elevate to root
if [[ $EUID -ne 0 ]]; then
    sudo su -s "$0"
    exit
fi

# Stop all containers
echo "Stopping containers."
docker ps | grep "_container" | awk '{print $1}' | xargs docker stop

# Remove containers
echo "Removing containers"
docker ps -a | grep "_container" | awk '{print $1}' | xargs docker rm

# Remove images
removeImages=""
printf "Remove Spigot and Bungee docker images? (y/n): "
read removeImages
if [ "$removeImages" == "y" ]; then
    echo "Removing images"
    docker rmi bungee
    docker rmi spigotmc
fi

# Clean data
removeData=""
printf "Remove container data? (y/n): "
read removeData
if [ "$removeData" == "y" ]; then
    echo "Removing all data files."
    rm -rf /srv/server-data
fi

# Clean Java
removeJava=""
printf "Remove Java and Buildtools? (y/n): "
read removeJava
if [ "$removeJava" == "y" ]; then
    rm -rf /opt/buildtools
    rm -ff /opt/java
fi

echo "Done!"
