#!/bin/bash
# Cleans out all docker images, containers and container data.

# Stop all containers
echo "Stopping containers."
docker ps | grep "_container" | awk '{print $1}' | xargs docker stop

# Remove containers
echo "Removing containers"
docker ps -a | grep "_container" | awk '{print $1}' | xargs docker rm

# Remove images
echo "Removing images"
docker rmi bungee
docker rmi spigotmc

# Clean data
echo "Removing all data files."
rm -rf /srv/server-data

echo "Done!"
