#!/bin/bash
# Start and stop Minecraft related docker containers

case $1 in 
    start)
        echo "Starting containers."
        docker ps -a | grep "_container" | awk '{print $1}' | xargs docker start
        echo "Containers started!"
        ;;
    stop)
        echo "Stopping containers."
        docker ps | grep "_container" | awk '{print $1}' | xargs docker stop
        echo "Containers stopped!"
        ;;
    *)
        echo "Tool for starting and stopping Mincraft related docker containers."
        echo "Usage: containerctl [start|stop]"
        ;;
esac