#!/bin/bash
# Start all containers

echo "Starting servers."

docker start lobby_container
docker start host1_container
docker start host2_container
docker start bungeecord_container

printf "\nServers started!\n"
