#!/bin/bash
# Stop all containers

echo "Stopping servers."

docker stop bungeecord_container
docker stop lobby_container
docker stop host1_container
docker stop host2_container

printf "\nServers stopped!\n"
